# Generated by Django 3.2.9 on 2021-11-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('dose_date', models.DateField()),
            ],
        ),
    ]
